#!/usr/bin/env python3
"""Using starmap()
"""

#end_pymotw_header
from itertools import *

values = [[0, 5], [1, 6], (2, 7), (3, 8), (4, 9)]

# The starmap() function is similar to map(), but instead of constructing a tuple from multiple iterators,
# it splits up the items in a single iterator as arguments to the mapping function using the * syntax.
for i in starmap(lambda x, y: (x, y, x * y), values):
    print('{} * {} = {}'.format(*i))




l = ['USA ',
     'CANADA ',
     'IRELAND ',
     'GERMANY ',
     'FRANCE ',
     'JAPAN ',
     'CHINA ',
     'AUSTRALIA ',
     'UK ',
     'NETHERLANDS ',
     'SINGAPORE ',
     'SWEDEN ',
     'NEW ZEALAND ',
     'ARGENTINA ',
     'AUSTRIA ',
     'BELGIUM ',
     'BOLIVIA ',
     'BRAZIL ',
     'CHILE ',
     'COLUMBIA ',
     'COSTA RICA ',
     'CZECH REPUBLIC ',
     'DENMARK ',
     'ECUADOR ',
     'FINLAND ',
     'GREECE ',
     'GUATEMALA ',
     'HONDURAS ',
     'HONG KONG ',
     'HUNGARY ',
     'INDIA ',
     'INDONESIA ',
     'ISRAEL ',
     'ITALY ',
     'KOREA ',
     'LUXEMBOURG ',
     'MACAU ',
     'MALAYSIA ',
     'MEXICO ',
     'MONACO ',
     'MOROCCO ',
     'NEW CALEDONIA ',
     'NORWAY ',
     'PANAMA ',
     'PARAGUAY ',
     'PERU ',
     'PHILIPPINES ',
     'POLAND ',
     'PORTUGAL ',
     'PUERTO RICO ',
     'RUSSIA ',
     'SLOVENIA ',
     'SOUTH AFRICA ',
     'SPAIN ',
     'SWITZERLAND ',
     'TAIWAN ',
     'THAILAND ',
     'TURKEY ',
     'URUGUAY ',
     'VENEZUELA ',
     'VIETNAM ',
     'UNITED ARAB EMIRATES ',
     'UKRAINE ',
     'BULGARIA ',
     'CAMBODIA ',
     'BAHRAIN ',
     'KUWAIT ',
     'LEBANON ',
     'QATAR ',
     'ROMANIA ',
     'SAUDI ARABIA ']


c_list = ['USA',
          'CANADA',
          'IRELAND',
          'GERMANY',
          'FRANCE',
          'JAPAN',
          'CHINA',
          'AUSTRALIA',
          'UK',
          'NETHERLANDS',
          'SINGAPORE',
          'SWEDEN',
          'NEW_ZEALAND',
          'ARGENTINA',
          'AUSTRIA',
          'BELGIUM',
          'BOLIVIA',
          'BRAZIL',
          'CHILE',
          'COLUMBIA',
          'COSTA_RICA',
          'CZECH_REPUBLIC',
          'DENMARK',
          'ECUADOR',
          'FINLAND',
          'GREECE',
          'GUATEMALA',
          'HONDURAS',
          'HONG_KONG',
          'HUNGARY',
          'INDIA',
          'INDONESIA',
          'ISRAEL',
          'ITALY',
          'KOREA',
          'LUXEMBOURG',
          'MACAU',
          'MALAYSIA',
          'MEXICO',
          'MONACO',
          'MOROCCO',
          'NEW_CALEDONIA',
          'NORWAY',
          'PANAMA',
          'PARAGUAY',
          'PERU',
          'PHILIPPINES',
          'POLAND',
          'PORTUGAL',
          'PUERTO_RICO',
          'RUSSIA',
          'SLOVENIA',
          'SOUTH_AFRICA',
          'SPAIN',
          'SWITZERLAND',
          'TAIWAN',
          'THAILAND',
          'TURKEY',
          'URUGUAY',
          'VENEZUELA',
          'VIETNAM',
          'UNITED_ARAB_EMIRATES',
          'UKRAINE',
          'BULGARIA',
          'CAMBODIA',
          'BAHRAIN',
          'KUWAIT',
          'LEBANON',
          'QATAR',
          'ROMANIA',
          'SAUDI_ARABIA']

for c in c_list:
    print("{{ id: CountryID.{}, name: CountryName.{} }},".format(c, c))

